# Generated by Django 2.2.6 on 2019-10-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ac_token',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
