# Generated by Django 2.2.6 on 2019-10-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0002_user_ac_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ac_token',
            field=models.TextField(blank=True),
        ),
    ]
