# Generated by Django 2.2.6 on 2019-10-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0003_auto_20191026_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_id',
            field=models.TextField(blank=True),
        ),
    ]
